### ISSUE TITLE
clang 3.6 packages

### ISSUE THREAD

**Issue by jgsogo** [lasote/conan-bzip2#2]
I'm building a project using conan and boost-1.60, but if fails to compile in clang 3.6 (using travis)

Project is [here](https://github.com/jgsogo/neutron/tree/master/processing/compute_informer_order) with its [conanfile](https://github.com/jgsogo/neutron/blob/master/processing/compute_informer_order/conanfile.txt).
Travis file is [this](https://github.com/jgsogo/neutron/blob/master/.travis.yml), now trying with `--build bzip2` [here](https://travis-ci.org/jgsogo/neutron/jobs/125502092).

Conan for this configuration is called using:

`conan install -s compiler=clang -s compiler.version=3.6 -s compiler.libcxx=libstdc++11 --build bzip2`

**Comment by lasote** [comment]
Its solved right?

**Comment by jgsogo** [comment]
It compiles, yes. Although it will be better to have these packages uploaded to conan server, won't it?

**Comment by lasote** [comment]
Yes, should be great. I we haven't done it yet it's because we already generate more than 100 packages for each Boost version, If we introduce clang and its versions... it can be crazy to maintain. I would like to develop some improvements to conan-package-tools to have custom clang docker images for this purpose first.
